# Generated by Django 3.1.7 on 2021-03-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="organisations",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="organisations",
            field=models.ManyToManyField(to="gateway.Organisation"),
        ),
    ]
