# Generated by Django 3.2 on 2021-05-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0002_output"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Output",
        ),
    ]
