# Generated by Django 3.2.2 on 2021-05-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0003_delete_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="organisations",
            field=models.ManyToManyField(blank=True, to="gateway.Organisation"),
        ),
    ]
