export DEV_USERID := `id -u`
export DEV_GROUPID := `id -g`

# Load .env files by default
set dotenv-load := true

# enable modern docker build features
export DOCKER_BUILDKIT := "1"


build env="dev":
    #!/usr/bin/env bash
    set -euo pipefail

    repo_root=$(git rev-parse --show-toplevel)

    # set build args for prod builds
    export BUILD_DATE=$(date -u +'%y-%m-%dT%H:%M:%SZ')
    export GITREF=$(git rev-parse --short HEAD)

    export PYTHON_VERSION=$(tr -d '[:space:]' < "$repo_root/.python-version")
    export NODE_VERSION=$(tr -d '[:space:]' < "$repo_root/.node-version")
    export UV_VERSION=$(sed -n 's/^required-version = ">=\([^\"]*\)".*/\1/p' "$repo_root/pyproject.toml")
    export JUST_VERSION=$(sed -n "s/^set minimum-version := '\([^']*\)'.*/\1/p" "$repo_root/justfile")

    # build the thing
    docker compose build --pull \
        --build-arg PYTHON_VERSION="$PYTHON_VERSION" \
        --build-arg NODE_VERSION="$NODE_VERSION" \
        --build-arg UV_VERSION="$UV_VERSION" \
        --build-arg JUST_VERSION="$JUST_VERSION" \
        {{ env }}


# copy built node assets back to host
copy-assets: build
    #!/usr/bin/env bash
    docker compose build --pull node-assets
    docker compose run --rm --no-deps --entrypoint /usr/bin/env node-assets rsync --delete -r /usr/src/app/assets/dist/ /app/assets/dist/


# run tests in docker container
test *args="":
    just build test
    docker compose run --rm test {{ args }}


# run dev server in docker container
serve:
    just build dev
    docker compose up dev


# run command in dev container
run *args="bash":
    just build dev
    docker compose run dev {{ args }}


# exec command in existing dev container
exec *args="bash":
    docker compose exec dev {{ args }}
