# Generated by Django 3.2 on 2021-05-06 11:23

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="output",
            name="authors",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="output",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description to display before rendered output",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="last_updated",
            field=models.DateField(
                blank=True,
                help_text="File last modified date; autopopulated from GitHub",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="publication_date",
            field=models.DateField(
                default=datetime.datetime.today,
                help_text="Date published; defaults to today",
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
