# Generated by Django 3.2.2 on 2021-05-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_output_cache_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="output",
            name="use_git_blob",
            field=models.BooleanField(default=False),
        ),
    ]
