# Generated by Django 3.2.2 on 2021-05-25 10:05

from django.db import migrations, models

import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0009_rename_output_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_html_file_path",
            field=models.CharField(
                default="dummy",
                help_text="Path to the output html file within the repo",
                max_length=255,
                validators=[reports.models.validate_html_filename],
            ),
            preserve_default=False,
        ),
    ]
