# Generated by Django 3.2.2 on 2021-05-25 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0009_rename_output_report"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="output_html_file_path",
            new_name="report_html_file_path",
        )
    ]
