# Generated by Django 3.2.2 on 2021-05-25 10:05

from django.db import migrations


def populate_report_html_file_path(apps, schema_editor):
    """Forwards migration replaces report_html_file_path with the contents of the old output_html_file_path field"""
    Report = apps.get_model("reports", "Report")
    for report in Report.objects.all():
        report.report_html_file_path = report.output_html_file_path
        report.save()


def populate_output_html_file_path(apps, schema_editor):
    """Backwards migration replaces output_html_file_path with the contents of the report_html_file_path field"""
    Report = apps.get_model("reports", "Report")
    for report in Report.objects.all():
        report.output_html_file_path = report.report_html_file_path
        report.save()


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0010_report_report_html_file_path"),
    ]

    operations = [
        migrations.RunPython(
            populate_report_html_file_path, populate_output_html_file_path
        )
    ]
