# Generated by Django 3.2.2 on 2021-05-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0011_datamigration_populate_report_html_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="output_html_file_path",
        ),
    ]
