# Generated by Django 3.2.2 on 2021-05-26 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0011_rename_help_texts_and_related_category_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name",), "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="report",
            options={"ordering": ("menu_name",)},
        ),
    ]
