# Generated by Django 3.2.2 on 2021-05-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0013_report_is_draft"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "ordering": ("menu_name",),
                "permissions": [("view_draft", "Can view draft reports")],
            },
        ),
    ]
