# Generated by Django 3.2.2 on 2021-06-02 17:21

import django_extensions.db.fields
from django.db import migrations
from django.utils.text import slugify


def populate_slug_from_name(apps, _):
    Category = apps.get_model("reports", "Category")
    for category in Category.objects.all():
        if not category.slug:
            category.slug = slugify(category.name)
            category.save()


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0017_make_report_description_non_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from=("name",)
            ),
        ),
        migrations.RunPython(
            code=populate_slug_from_name,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from=("name",), unique=True
            ),
        ),
    ]
