# Generated by Django 3.2.2 on 2021-06-03 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0017_make_report_description_non_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("paper", "Paper"),
                            ("link", "Link"),
                        ],
                        default="link",
                        help_text="Icon to display with this link",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="A short name/description of this link",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="reports.report",
                    ),
                ),
            ],
        ),
    ]
