# Generated by Django 3.2.2 on 2021-06-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0018_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="link",
            options={
                "verbose_name_plural": "Related Links (note that a link to the source code repo will be automatically generated on save)"
            },
        ),
        migrations.AlterField(
            model_name="report",
            name="publication_date",
            field=models.DateField(help_text="Date of first publication"),
        ),
    ]
