# Generated by Django 3.2.6 on 2021-09-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0019_link_verbose_name_report_publication_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="doi",
            field=models.URLField(
                blank=True,
                help_text="DOI for this report; note DOIs for associated publications should be entered as associated Links",
                null=True,
            ),
        ),
    ]
