# Generated by Django 3.2.6 on 2022-01-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0020_report_doi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="doi",
            field=models.URLField(
                blank=True,
                help_text="DOI for this report; note DOIs for associated publications should be entered as associated Links",
                null=True,
                verbose_name="DOI",
            ),
        ),
    ]
