# Generated by Django 4.0.3 on 2022-07-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0022_add_report_job_server_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="last_updated",
            field=models.DateField(
                blank=True,
                help_text="File last modified date; autopopulated from the file origin",
                null=True,
                verbose_name="Last released",
            ),
        ),
    ]
