# Generated by Django 4.1.1 on 2022-09-27 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0023_alter_report_last_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Org",
            options={"verbose_name": "Organisation"},
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("logo", models.FileField(null=True, upload_to="org_logos/")),
                ("url", models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name="report",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="reports.org",
            ),
        ),
    ]
