# Generated by Django 4.1.1 on 2022-09-27 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0025_set_bennett_as_default_org"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="reports.org",
            ),
        ),
    ]
