# Generated by Django 4.1.1 on 2022-09-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0026_require_org_on_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="is_external",
            field=models.BooleanField(default=False),
        ),
    ]
