# Generated by Django 4.1.2 on 2022-10-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0032_require_created_and_updated_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="link",
            options={"verbose_name_plural": "Related Links"},
        ),
    ]
