# Generated by Django 4.1.2 on 2022-10-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0033_update_links_verbose_plural"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="is_draft",
            field=models.BooleanField(
                default=True,
                help_text="Draft reports are only visible by a logged in user with relevant permissions",
            ),
        ),
    ]
