# Generated by Django 3.2.2 on 2021-05-12 08:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outputs", "0002_front_matter_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="output",
            name="cache_token",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
