# Generated by Django 3.2.2 on 2021-05-12 15:36

from django.db import migrations


def add_default_category(apps, schema_editor):
    # We can't import the Category/Output models directly as they may be a newer
    # version than this migration expects. We use the historical version.
    Category = apps.get_model("outputs", "Category")
    Output = apps.get_model("outputs", "Output")
    category, _ = Category.objects.get_or_create(name="Reports")
    for output in Output.objects.all():
        output.category = category
        output.save()


class Migration(migrations.Migration):

    dependencies = [
        ("outputs", "0005_category"),
    ]

    operations = [migrations.RunPython(add_default_category, migrations.RunPython.noop)]
