# Generated by Django 3.2.2 on 2021-05-14 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outputs", "0007_make_output_category_non_nullable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterField(
            model_name="output",
            name="category",
            field=models.ForeignKey(
                help_text="Output category; used for navigation",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outputs",
                to="outputs.category",
            ),
        ),
        migrations.AlterField(
            model_name="output",
            name="publication_date",
            field=models.DateField(help_text="Date published"),
        ),
    ]
