# Generated by Django 3.2.2 on 2021-05-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("outputs", "0008_output_ondelete_protection_help_text_and_plural_names"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Output",
            new_name="Report",
        ),
    ]
