name: "CI"

env:
  IMAGE_NAME: "reports"
  PUBLIC_IMAGE_NAME: "ghcr.io/opensafely-core/reports"
  REGISTRY: "ghcr.io"
  SSH_AUTH_SOCK: "/tmp/agent.sock"

on:
  push:
  workflow_dispatch:

permissions:
  contents: "read"

jobs:
  check:
    name: "Lint: Python"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          persist-credentials: false

      - name: "Install uv"
        uses: "astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9" # v9.0.0
        with:
          version-file: "pyproject.toml"
          enable-cache: false

      - name: "Install Python"
        run: "uv python install"

      - name: "Install Just"
        uses: "extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3" # v4.0.0
        with:
          just-version: "1.57.0"

      - name: "Check formatting, linting and import sorting"
        run: "just check"

  test:
    needs: ["check"]
    name: "Test: Python"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          persist-credentials: false

      - name: "Install uv"
        uses: "astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9" # v9.0.0
        with:
          version-file: "pyproject.toml"
          enable-cache: false

      - name: "Install Python"
        run: "uv python install"

      - name: "Install Just"
        uses: "extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3" # v4.0.0
        with:
          just-version: "1.57.0"

      - name: "Install Node.js"
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: ".node-version"

      - name: "Build assets"
        run: "just assets"
        env:
          SECRET_KEY: 12345

      - name: "Run tests"
        env:
          SECRET_KEY: 12345
          REQUESTS_CACHE_NAME: "test_cache"
          SOCIAL_AUTH_NHSID_KEY: "dummy-client-id"
          SOCIAL_AUTH_NHSID_SECRET: "dummy-secret"
          SOCIAL_AUTH_NHSID_API_URL: "https://dummy-nhs.net/oidc"
          ASSETS_DEV_MODE: True
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "just test"

  lint-dockerfile:
    name: "Lint: Docker"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          persist-credentials: false

      - uses: "hadolint/hadolint-action@2a66e89f53d0771bb131a7fa31f3136336094aa6" # v3.4.0
        with:
          dockerfile: "docker/Dockerfile"

  docker-test:
    needs: ["check", "lint-dockerfile"]
    name: "Test: Python in Docker"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          persist-credentials: false

      - name: "Install Just"
        uses: "extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3" # v4.0.0
        with:
          just-version: "1.57.0"

      - name: "Build docker image and run tests in it"
        run: "just docker test"

  # deploy:
  #   needs: [test, docker-test, lint-dockerfile]

  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: read
  #     packages: write

  #   if: github.ref == 'refs/heads/main'

  #   concurrency: deploy-production

  #   steps:
  #     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
  #       with:
  #         persist-credentials: false
  #     - uses: "opensafely-core/setup-action@d9171097dd0d37bdb7bed58f701eb03ff317ed17" # v1.7.0
  #       with:
  #         install-just: true

  #     - name: Build docker image
  #       run: |
  #         # docker-test step will build the dev image by default, so build the prod image
  #         just docker-build prod

  #     - name: Login to Packages Container registry
  #       run: |
  #         docker login $REGISTRY -u ${GITHUB_ACTOR} --password ${{ secrets.GITHUB_TOKEN }}

  #     - name: publish docker image
  #       run: |
  #         docker tag $IMAGE_NAME $PUBLIC_IMAGE_NAME:latest
  #         docker push $PUBLIC_IMAGE_NAME:latest

  #     - name: Setup SSH Agent
  #       run: |
  #         ssh-agent -a $SSH_AUTH_SOCK > /dev/null
  #         ssh-add - <<< "${{ secrets.DOKKU3_DEPLOY_SSH_KEY }}"

  #     - name: Deploy
  #       run: |
  #         SHA=$(docker inspect --format='{{join .RepoDigests "\n"}}' "$PUBLIC_IMAGE_NAME:latest" | grep "$PUBLIC_IMAGE_NAME")
  #         echo "Deploying $SHA to dokku3"
  #         ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" dokku@dokku3.ebmdatalab.net git:from-image reports $SHA

  #     - name: Create Sentry release
  #       uses: getsentry/action-release@ff07929a6537bac57790c3451cf4d364aca38528 # v3.7.0
  #       env:
  #         SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_RELEASE_INTEGRATION_TOKEN }}
  #         SENTRY_ORG: ebm-datalab
  #         SENTRY_PROJECT: reports
  #       with:
  #         environment: production
  #         ignore_empty: true
