name: Update python dependencies

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 8 * * 1"

permissions:
  contents: read
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.1
    - uses: "opensafely-core/setup-action@v1"
      with:
        python-version: "3.12"
        install-just: true

    - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
      id: generate-token
      with:
        app-id: 1031449  # opensafely-core Create PR app
        private-key: ${{ secrets.CREATE_PR_APP_PRIVATE_KEY }}

    - uses: bennettoxford/update-dependencies-action@d9d335323c713d00eee39dbf0fae357e144729f0 # v1
      with:
        token: ${{ steps.generate-token.outputs.token }}
